config/routes.rb
Rails.application.routes.draw do

  resources :visits, only: [:index]

  namespace :door_event do
    resources :opened, only: [:create]
    resources :closed, only: [:create]
  end

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  include MessageText

  validates :text, inclusion: { in: VALID_MESSAGES }
  validates :nickname, inclusion: { in: CHAT_NAMES }

  after_commit :push_message

  def name
    self.nickname
  end

  private

  def push_message
    ChatAllChannel.push_message(self)
  end
end

app/models/concerns/message_text.rb
module MessageText
  VALID_MESSAGES = ['😁', '😂', '😍', '😖', '😨', '🙈', '🚀']

  # Terrible storage for chat names
  CHAT_NAMES = [
    '4-LOM',
    'Aayla Secura',
    'Admiral Ackbar',
    'Admiral Thrawn',
    'Ahsoka Tano',
    'Anakin Solo',
    'Asajj Ventress',
    'Aurra Sing',
    'Senator Bail Organa',
    'Barriss Offee',
    'Bastila Shan',
    'Ben Skywalker',
    'Bib Fortuna',
    'Biggs Darklighter',
    'Boba Fett',
    'Bossk',
    'Brakiss',
    'C-3PO',
    'Cad Bane',
    'Cade Skywalker',
    'Callista Ming',
    'Captain Rex',
    'Carnor Jax',
    'Chewbacca',
    'Clone Commander Cody',
    'Count Dooku',
    'Darth Bane',
    'Darth Krayt',
    'Darth Maul',
    'Darth Nihilus',
    'Darth Vader',
    'Dash Rendar',
    'Dengar',
    'Durge',
    'Emperor Palpatine',
    'Exar Kun',
    'Galen Marek',
    'General Crix Madine',
    'General Dodonna',
    'General Grievous',
    'General Veers',
    'Gilad Pellaeon',
    'Grand Moff Tarkin',
    'Greedo',
    'Han Solo',
    'IG 88',
    'Jabba The Hutt',
    'Jacen Solo',
    'Jaina Solo',
    'Jango Fett',
    'Jarael',
    'Jerec',
    'Joruus C\'Baoth',
    'Ki-Adi-Mundi',
    'Kir Kanos',
    'Kit Fisto',
    'Kyle Katarn',
    'Kyp Durron',
    'Lando Calrissian',
    'Luke Skywalker',
    'Luminara Unduli',
    'Lumiya',
    'Mace Windu',
    'Mara Jade',
    'Mission Vao',
    'Natasi Daala',
    'Nom Anor',
    'Obi-Wan Kenobi',
    'Padmé Amidala',
    'Plo Koon',
    'Pre Vizsla',
    'Prince Xizor',
    'Princess Leia',
    'PROXY',
    'Qui-Gon Jinn',
    'Quinlan Vos',
    'R2-D2',
    'Rahm Kota',
    'Revan',
    'Satele Shan',
    'Savage Opress',
    'Sebulba',
    'Shaak Ti',
    'Shmi Skywalker',
    'Talon Karrde',
    'Ulic Qel-Droma',
    'Visas Marr',
    'Watto',
    'Wedge Antilles',
    'Yoda',
    'Zam Wesell',
    'Zayne Carrick',
    'Zuckuss'
  ]
end

app/models/current_state.rb
class CurrentState
  class << self
    def bs_alert
      opened? ? 'success' : 'danger'
    end

    def color
      opened? ? 'green' : 'red'
    end

    def door_state
      opened? ? 'open' : 'closed'
    end

    def opened?
      Visit.last.end_at.present?
    end

    def push_state
      ActionCable.server.broadcast(
        "DoorEventChannel",
        state: door_state,
        color: color,
        alertState: bs_alert,
        connectedCnt: ActionCable.server.connections.length,
      )
    end
  end
end

app/models/door_event.rb
class DoorEvent < ApplicationRecord
  CLOSED = 'closed'
  OPENED = 'opened'

  belongs_to :visit, required: false

  enum action: [CLOSED, OPENED]

  after_commit { process_event }

  private

  def process_event
    visit = nil
    if self.closed?
      if Visit.first.nil? || Visit.last.end_at
        visit = Visit.create!(start_at: self.created_at)
      end
    else
      visit = Visit.last
      if !visit.end_at.present?
        visit.update(end_at: self.created_at)
      end
    end

    self.update_columns(visit_id: visit.id) if visit
  end

end

app/models/visit.rb
class Visit < ApplicationRecord
  has_many :door_events

  after_commit { CurrentState.push_state }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/door_event/closed_controller.rb
class DoorEvent::ClosedController < ApplicationController
  def create
    event = DoorEvent.create!(action: DoorEvent::CLOSED)

    render json: event.to_json
  end
end

app/controllers/door_event/opened_controller.rb
class DoorEvent::OpenedController < ApplicationController
  def create
    event = DoorEvent.create!(action: DoorEvent::OPENED)

    render json: event.to_json
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    time_now = Time.zone.now

    @todays_visits = Visit.where(start_at: time_now.beginning_of_day .. time_now).order(start_at: :desc)

    @icon_color = CurrentState.color

    set_stats_alltime
    set_stats_lastused

    set_chat_user
    load_chat_all
  end

  private

  def load_chat_all
    @recent_chat = ChatMessage.order(created_at: :desc).limit(20)
  end

  def set_chat_user
    @nickname ||= ChatMessage::CHAT_NAMES.sample

    ActionCable.server.broadcast(
      'who_connected',
      html: "Welcome <b>#{@nickname}</b> who just connected.<br/>".html_safe,
    )
  end

  def set_stats_alltime
    visits = Visit.where.not(end_at: nil).order(start_at: :asc)

    @alltime_visits_by_hour = visits_by_hour(visits)
    @alltime_total_time = visits_total_time(visits)
    @alltime_visits = visits_duration_sorted(visits)
  end

  def set_stats_lastused
    time_now = Time.zone.now
    yesterday = time_now - 1.day

    # Last used that was not today
    @last_used_at = Visit.where('start_at < ?', yesterday.end_of_day).last.start_at

    visits = Visit.where(
      start_at: @last_used_at.beginning_of_day .. @last_used_at.end_of_day
    ).where.not(
      end_at: nil
    ).order(start_at: :asc)

    @last_used_day_visits_by_hour = visits_by_hour(visits)
    @last_used_day_total_time = visits_total_time(visits)
    @last_used_day_visits = visits_duration_sorted(visits)
  end

  def visits_duration_sorted(visits)
    visits.sort_by do |visit|
      (visit.end_at - visit.start_at).to_i
    end
  end

  def visits_by_hour(visits)
    Hash[
      visits.group_by do |visit|
        visit.start_at.strftime('%l %P')
      end.sort do |a, b|
        DateTime.parse(a[0]) <=> DateTime.parse(b[0])
      end
    ]
  end

  def visits_total_time(visits)
    visits.map do |visit|
      (visit.end_at - visit.start_at).to_i
    end.compact.inject(&:+)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    time_now = Time.zone.now

    @visits = Visit.order(start_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def duration_hms(obj, format = '%H:%M:%S')
    seconds = if obj.is_a?(Visit)
                (obj.end_at - obj.start_at).to_i
              else
                obj
              end

    Time.at(seconds).utc.strftime(format)
  end
end

app/helpers/closed_helper.rb
module ClosedHelper
end

app/helpers/door_events_helper.rb
module DoorEventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opened_helper.rb
module OpenedHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/chats/_all.html.slim
#chat-all-messages
  - messages.each do |message|
    = render partial: 'chats/message', locals: { message: message }

app/views/chats/_message.html.slim
p
  dl.dl-horizontal
    dt = message.name
    dd = "(#{message.created_at.strftime('%I:%M')}) #{message.text}"

app/views/chats/_selectable_messages.html.slim
.row
  .col-xs-12
    .send-text-container.pull-left
      h5.send-text-header.pull-left
        | I'm Feeling:

      - ChatMessage::VALID_MESSAGES.each do |text|
        span.emoji-message.pull-left = text

    .display-nickname.pull-right
      | nickname:
      b
        span#nickname
          = @nickname
    .divider

app/views/home/_stats.html.slim
javascript:
  var labels = #{visits_by_hour.keys.to_json.html_safe}
  var data = #{visits_by_hour.values.map(&:count).to_json.html_safe}

#stats-area
  .row
    .col-xs-12
      h2 ="#{date.strftime("%A")}'s, #{date.strftime('%d/%m')}, Stats"
  .row
    .col-xs-12
      dl.dl-horizontal
        dt Total Visits
        dd = visits.count
        dt Total Time
        dd = duration_hms(total_time)
        dt Average
        dd = duration_hms(total_time/visits.count)
        dt Shortest
        dd = duration_hms(visits.first)
        dt Longest
        dd = duration_hms(visits.last)
  .row
    .col-xs-12
      canvas#myChart[width="400" height="200"]

app/views/home/_stats_alltime.html.slim
javascript:
  var labelsAllTime = #{visits_by_hour.keys.to_json.html_safe}
  var dataAllTime = #{visits_by_hour.values.map(&:count).to_json.html_safe}

#stats-area
  .row
    .col-xs-12
      h2 All Time Stats
  .row
    .col-xs-12
      dl.dl-horizontal
        dt Total Visits
        dd = visits.count
        dt Total Time
        dd = distance_of_time_in_words(Time.at(0), Time.at(total_time))
        dt Average
        dd = duration_hms(total_time/visits.count)
        dt Shortest
        dd = duration_hms(visits.first)
        dt Longest
        dd = duration_hms(visits.last)
  .row
    .col-xs-12
      canvas#statsAllTime[width="400" height="200"]

app/views/home/_stats_lastused.html.slim
javascript:
  var labelsLastUsed = #{visits_by_hour.keys.to_json.html_safe}
  var dataLastUsed = #{visits_by_hour.values.map(&:count).to_json.html_safe}

#stats-area
  .row
    .col-xs-12
      h2 ="#{date.strftime("%A")}'s, #{date.strftime('%b %d')}, Stats"
  .row
    .col-xs-12
      dl.dl-horizontal
        dt Total Visits
        dd = visits.count
        dt Total Time
        dd = duration_hms(total_time)
        dt Average
        dd = duration_hms(total_time/visits.count)
        dt Shortest
        dd = duration_hms(visits.first)
        dt Longest
        dd = duration_hms(visits.last)
  .row
    .col-xs-12
      canvas#statsLastUsed[width="400" height="200"]

app/views/home/index.html.slim
.row
  .col-sm-6
    h1
      | Level 3 Bathroom
    h1
      small 6 Jiak Chuan

    .row
      .col-sm-12
        h4
          small Current Status
        h4
          #current-state.alert[class="alert-#{CurrentState.bs_alert}"]
            = CurrentState.door_state

    .row
      .col-sm-12
        .form-group
          .togglebutton
            label
              | Notify of Next Open
              input#notify-me[type='checkbox']

    .row
      .col-sm-12
        dl.dl-horizontal
          dt Currently Connected
          dd#num-connected ?
  .col-sm-6
    = render partial: 'chats/selectable_messages'
    = render partial: 'chats/all', locals: { messages: @recent_chat }
.row
  .col-sm-6
    = render partial: 'stats_alltime', locals: { visits: @alltime_visits, visits_by_hour: @alltime_visits_by_hour, total_time: @alltime_total_time }
  .col-sm-6
    = render partial: 'stats_lastused', locals: { visits: @last_used_day_visits, visits_by_hour: @last_used_day_visits_by_hour, total_time: @last_used_day_total_time, date: @last_used_at }

.row
  .col-sm-3
    .well
      h1 Dev Room
      dl.dl-horizontal
        dt Temperature
        dd#dev-temp ?
        dt Humidity
        dd#dev-humidity ?

app/views/layouts/_navbar.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to 'Home', root_path
        li
          = link_to 'Visits', visits_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    title = "[#{CurrentState.door_state}] We Love Ruby SG"

    /! Material Design fonts
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Roboto:300,400,500,700"
    = stylesheet_link_tag "//fonts.googleapis.com/icon?family=Material+Icons"

    /! Bootstrap
    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"

    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = favicon_link_tag "/#{@icon_color}_square.ico"

  body
    = render partial: 'layouts/navbar'

    .container-fluid
      = yield

app/views/visits/_event_row.html.slim
tr
  td = visit.id
  td = visit.start_at.strftime('%l:%M:%S %P, %b %d')
  td = visit.end_at.strftime('%l:%M:%S %P, %b %d') if visit.end_at
  td
    - if visit.start_at && visit.end_at
      = distance_of_time_in_words(visit.start_at, visit.end_at, include_seconds: true)

app/views/visits/index.html.slim
.row
  .col-sm-6
    h1 Visits

    table.table
      thead
        th ID
        th Start
        th End
        th Duration
      tbody#events
        = render partial: 'event_row', collection: @visits, as: :visit